[package]
name = "docdoodler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.22"
img = { package = "image", version = "0.24.8" }
pdfium-render = "0.8.17"
